version: "3.1"
services:
  web:
    image: forte
    depends_on:
      - zookeeper
      - kafka
    secrets:
      - api_auth_certificate
      - google_oauth_credentials
    environment:
      KAFKA_CONSUMER_TOPIC: "forte-download"
      KAFKA_CONSUMER_BROKERS: kafka:9092
      YOUTUBEDL_DOWNLOAD_PATH: "/tmp/"
    volumes:
      - ./server:/app/server
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-rest:
    image: confluentinc/cp-kafka-rest
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_REST_HOST_NAME: localhost:8082
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
secrets:
  api_auth_certificate:
    file: ./server/secret/api_certificate.cred
  google_oauth_credentials:
    file: ./server/secret/google_oauth.cred
