version: "3"
services:
  web:
    image: forte
    ports:
      - "80:5000"
    networks:
      - webnet
  zookeeper:
    image: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
  kafka:
    image: ches/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      ZOOKEEPER_IP: zookeeper
  # kafka-rest:
  #   image: confluentinc/cp-kafka-rest
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     KAFKA_REST_HOST_NAME: 127.0.0.1
  #     KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
networks:
  webnet:
