apiVersion: v1
kind: Service
metadata:
  name: forte-app
spec:
  selector:
    app: forte
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: forte
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: forte
    spec:
      containers:
      - name: kafka-rest
        image: confluentinc/cp-kafka-rest:3.3.0
        env:
        - name: KAFKA_CONSUMER_TOPIC
          value: forte-download
        - name: KAFKA_CONSUMER_BROKERS
          value: cp-kafka:9092
        - name: YOUTUBEDL_DOWNLOAD_PATH
          value: /tmp/
        volumeMounts:
        - name: secrets
          mountPath: /run/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: forte-secrets
