apiVersion: v1
kind: Service
metadata:
  name: cp-kafka-rest
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: kafka-rest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-rest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
      - name: kafka-rest
        image: confluentinc/cp-kafka-rest:3.3.0
        ports:
        - containerPort: 8082
        env:
        - name: KAFKA_REST_HOST_NAME
          value: $(CP_KAFKA_REST_SERVICE_HOST):8082
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: zookeeper:2181
